module TranslatorHelper
 TZOLKIN_FANCY = ["Ajaw", "Imix", "Ik'", "Ak'bal", "K'an", "Chikchan", 
                    "Kimi", "Manik'", "Lamat", "Muluk", "Ok", "Chuwen", 
                    "Eb'", "B'en", "Ix", "Men", "Kib'", "Kab'an", "Etz'nab'", "Kawak"].freeze
    TZOLKIN_TRSCR = ["AJAW", "HA'?", "IK'", "AK'AB'", "OL", 
                    "?-CHAN", "CHAM?", "chi", "EK'", "?", "?", "?", "?", "?", 
                    "HIX?", "?", "?", "CHAB'", "?", "?"].freeze

    HAAB_FANCY = ["Pop", "Wo", "Sip", "Sotz'", "Sek", "Xul", "Yaxk'in", "Mol", 
                    "Ch'en", "Yax", "Sak", "Keh", "Mak", "Kank'in", "Muwan", "Pax", "K'ayab", "Kumk'u", "Wayeb"].freeze
    HAAB_TRSCR = ["K'AN-?-w(a)", "IK'-AT-(ta)", "CHAK-AT-(ta)", "SUTZ'", "ka-se-w(a)", "CHIK-n(i)", 
                    "YAX-K'IN-(ni)", "mo-l(o)", "IK'-SIHOM?-(ma)", "YAX-SIHOM?", "SAK-SIHOM?", "CHAK-SIHOM?", 
                    "ma-AK", "UNIW-(wa)", "MUWAN-(ni)", "PAX", "[KAN]a-si-y(a)", "?-OL-(la)", "ko-l(o)-AJAW"].freeze

    NUMERALS_FANCY = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", 
                    "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"].freeze
    NUMERALS_TRSCR = ["MIH", "JU'N", "CHA'", "OX", "CHAN", "HO'", "WAK", "HUK", "WAXAK", "B'OLON", "LAJU'N", "B'ULUK", 
                    "LAJCHAN", "OXLAJU'N", "CHANLAJU'N", "HO'LAJU'N", "WAKLAJU'N", "HUKLAJU'N", "WAXAKLAJU'N", "B'OLONLAJU'N"].freeze

    GLYPH_G_TRSCR = ["#{NUMERALS_TRSCR[9]}-CH'AM-K'UH", "K'UH-?", "?", "?", "#{NUMERALS_TRSCR[7]}-?","#{NUMERALS_TRSCR[5]}-?",
                    "#{NUMERALS_TRSCR[9]}-?", "NAH-?", "?", "?"].freeze
    FANCY = {           'baktun'    => "B'ak'tun",
                        'katun'     => "K'atun",
                        'tun'       => "Tun",
                        'winal'     => "Winal",
                        'kin'       => "K'in",
                        'ajaw'      => "Ajaw",
                        'imix'      => "Imix",
                        'ik'        => "Ik'",
                        'akbal'     => "Ak'bal",
                        'kan'       => "K'an", 
                        'chikchan'  => "Chikchan",
                        'kimi'      => "Kimi",
                        'manik'     => "Manik'",
                        'lamat'     => "Lamat",
                        'muluk'     => "Muluk",
                        'ok'        => "Ok",
                        'chuwen'    => "Chuwen",
                        'eb'        => "Eb'",
                        'ben'       => "B'en",
                        'ix'        => "Ix",
                        'men'       => "Men",
                        'kib'       => "Kib'",
                        'kaban'     => "Kab'an",
                        'etznab'    => "Etz'nab'",
                        'kawak'     => "Kawak",
                        'pop'       => "Pop",
                        'wo'        => "Wo",
                        'sip'       => "Sip",
                        'sotz'      => "Sotz'",
                        'sek'       => "Sek",
                        'xul'       => "Xul",
                        'yaxkin'    => "Yaxk'in",
                        'mol'       => "Mol",
                        'chen'      => "Ch'en",
                        'yax'       => "Yax",
                        'sak'       => "Sak",
                        'keh'       => "Keh",
                        'mak'       => "Mak",
                        'kankin'    => "Kank'in",
                        'muwan'     => "Muwan",
                        'pax'       => "Pax",
                        'kayab'     => "K'ayab",
                        'kumku'     => "Kumk'u",
                        'wayeb'     => "Wayeb",
                        0           => "zero",
                        1           => "one",
                        2           => "two",
                        3           => "three",
                        4           => "four",
                        5           => "five",
                        6           => "six",
                        7           => "seven",
                        8           => "eight",
                        9           => "nine",
                        10          => "ten",
                        11          => "eleven",
                        12          => "twelve",
                        13          => "thirteen",
                        14          => "fourteen",
                        15          => "fifteen",
                        16          => "sixteen",
                        17          => "seventeen",
                        18          => "eighteen",
                        19          => "nineteen"}.freeze

    TRANSCRIPTION = {   'baktun'    => "pi-h(i)",
                        'katun'     => "WINIK-HAB'",
                        'tun'       => "HAB'",
                        'winal'     => "WINIK",
                        'kin'       => "K'IN",
                        'ajaw'      => "AJAW",
                        'imix'      => "HA'?",
                        'ik'        => "IK'",
                        'akbal'     => "AK'AB",
                        'kan'       => "OL", 
                        'chikchan'  => "?-CHAN",
                        'kimi'      => "CHAM?",
                        'manik'     => "chi",
                        'lamat'     => "EK'",
                        'muluk'     => "?",
                        'ok'        => "?",
                        'chuwen'    => "?",
                        'eb'        => "?",
                        'ben'       => "?",
                        'ix'        => "HIX?",
                        'men'       => "?",
                        'kib'       => "?",
                        'kaban'     => "CHAB'",
                        'etznab'    => "?",
                        'kawak'     => "?",
                        'pop'       => "K'AN-?-w(a)",
                        'wo'        => "IK'-AT-(ta)",
                        'sip'       => "CHAK-AT-(ta)",
                        'sotz'      => "SUTZ'",
                        'sek'       => "ka-se-w(a)",
                        'xul'       => "CHIK-n(i)",
                        'yaxkin'    => "YAX-K'IN-(ni)",
                        'mol'       => "mo-l(o)",
                        'chen'      => "IK'-SIHOM?-(ma)",
                        'yax'       => "YAX-SIHOM?",
                        'sak'       => "SAK-SIHOM?",
                        'keh'       => "CHAK-SIHOM?",
                        'mak'       => "ma-AK",
                        'kankin'    => "UNIW-(wa)",
                        'muwan'     => "MUWAN-(ni)",
                        'pax'       => "PAX",
                        'kayab'     => "[KAN]a-si-y(a)",
                        'kumku'     => "?-OL-(la)",
                        'wayeb'     => "ko-l(o)-AJAW",
                        0           => "MIH",
                        1           => "JU'N",
                        2           => "CHA'",
                        3           => "OX",
                        4           => "CHAN",
                        5           => "HO'",
                        6           => "WAK",
                        7           => "HUK",
                        8           => "WAXAK",
                        9           => "B'OLON",
                        10          => "LAJU'N",
                        11          => "B'ULUK",
                        12          => "LAJCHAN",
                        13          => "OXLAJU'N",
                        14          => "CHANLAJU'N",
                        15          => "HO'LAJU'N",
                        16          => "WAKLAJU'N",
                        17          => "HUKLAJU'N",
                        18          => "WAXAKLAJU'N",
                        19          => "B'OLONLAJU'N",
                        'G1'        => "B'OLON-CH'AM-K'UH",
                        'G2'        => "K'UH-?",
                        'G3'        => "?",
                        'G4'        => "?",
                        'G5'        => "HUK-?",
                        'G6'        => "HO'-?",
                        'G7'        => "B'OLON-?",
                        'G8'        => "NAH-?",
                        'G9'        => "?"}.freeze
end
